project:
  type: book
  output-dir: docs

book:
  title: "Kirjallisuuskatsauksen ohje"
  author: "Oliver Saal"
  
  chapters:
    - index.qmd
    - part: "Kriteeristö"
      chapters: 
        - kriteeristo.qmd
        - krit-aika.qmd
        - krit-metodologia.qmd
        - krit-kohderyhma.qmd
        - krit-maantiede.qmd
        - krit-tutkimuskieli.qmd
        - krit-aineistotyyppi.qmd
        - krit-tietokannat.qmd
    - tietolahteet.qmd
    - hakeminen.qmd
    - dokumentointi.qmd
    - hakulausekkeet.qmd
  
  navbar:
    background: primary
    search: true
    left:
      - text: "Etusivu"
        file: index.qmd
      - sidebar:kriteeristo
      - sidebar:tietolahteet
      - sidebar:hakeminen
      - sidebar:dokumentointi
      - hakulausekkeet.qmd
  
  sidebar:
    - id: kriteeristo
      title: "Kriteeristö"
      style: "docked"
      background: primary
      collapse-level: 2
      contents:
        - kriteeristo.qmd
        - krit-aika.qmd
        - krit-metodologia.qmd
        - krit-kohderyhma.qmd
        - krit-maantiede.qmd
        - krit-tutkimuskieli.qmd
        - krit-aineistotyyppi.qmd
        - krit-tietokannat.qmd
        
    - id: tietolahteet
      title: "Tietolähteet"
      contents:
        - tietolahteet.qmd
        
    - id: hakeminen
      title: "Hakujen suorittaminen"
      contents:
        - hakeminen.qmd
        
    - id: dokumentointi
      title: "Dokumentointi"
      contents:
        - dokumentointi.qmd

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    lang: fi
    crossref:
      chapters: true

editor: visual

